name: Publish to Maven & Create GitHub Release

on:
  push:
    branches:
      - version/*
  workflow_dispatch:

jobs:
  build:
    uses: SLNE-Development/surf-workflows/.github/workflows/build-publish-release-gradle.yml@master
    with:
      modules: "surf-transaction-paper-*-all.jar;surf-transaction-velocity-*-all.jar;surf-transaction-microservice-*-all.jar"
      check-kotlin-abi: true
    secrets: inherit